language: php

php:
  - 5.5
  - 5.4
  - hhvm

env:
- SYMFONY_VERSION=2.4.*
- SYMFONY_VERSION=2.5.*
- SYMFONY_VERSION=2.6.*

before_script: composer require symfony/event-dispatcher:${SYMFONY_VERSION} \
                                symfony/config:${SYMFONY_VERSION} \
                                symfony/dependency-injection:${SYMFONY_VERSION} \
                                symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit --coverage-text
